#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ToDoApp.Resource", IsApplication=true)]

namespace ToDoApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Main
		{
			
			// aapt resource value: 0x7f070002
			public const int btnSync = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int lblHeading = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int lstTodoItems = 2131165185;
			
			static Main()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Main()
			{
			}
		}
		
		public partial class TodoItemDetailRow
		{
			
			// aapt resource value: 0x7f080003
			public const int ChkCompleted = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int Layout = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int LinearLayout = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int TxtCreated = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int TxtDescription = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int TxtUpdated = 2131230725;
			
			static TodoItemDetailRow()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private TodoItemDetailRow()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int button = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int buttondisabled = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int buttonpressed = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int @checked = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CustomCheckbox = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int @unchecked = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TodoItemDetailRow = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Background = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int Button = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Button_Centre = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Button_CentreBottom = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Button_Left = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Button_Right = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int MediumText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MediumText_Bold = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int SmallText = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int SmallText_Bold = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int SmallText_Grey = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
